name: 'AutoCoder'
description: 'This action automates generating code from GitHub issues using OpenAI ChatGPT and creates a pull request with the generated code for review.'
author: 'Your Name or Organization'
inputs:
  GITHUB_TOKEN:
    description: 'Personal access token (PAT) used for GitHub API authentication. Required for creating pull requests and repository interactions.'
    required: true
  REPOSITORY:
    description: 'The repository where the action will execute.'
    required: true
  ISSUE_NUMBER:
    description: 'The number of the issue that triggered the action.'
    required: true
  OPENAI_API_KEY:
    description: 'API key for OpenAI, used for interacting with ChatGPT to generate code from issue descriptions.'
    required: true
  SCRIPT_PATH:
    description: 'The path to the script that interacts with ChatGPT and generates code.'
    required: true
  LABEL:
    description: 'Label that triggers the action.'
    required: true
    default: 'autocoder-bot'
outputs:
  pull_request_url:
    description: 'URL of the auto-created pull request containing generated code for review.'
runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Greet Users
      run: echo "Hello, welcome to AutoCoder! Let's generate some code."
      shell: bash
    - name: Make script executable
      run: chmod +x ${{ inputs.SCRIPT_PATH }}
      shell: bash
    - name: Generate Code from Issue
      run: |
        ${{ inputs.SCRIPT_PATH }} "${{ inputs.GITHUB_TOKEN }}" "${{ inputs.REPOSITORY }}" "${{ inputs.ISSUE_NUMBER }}" "${{ inputs.OPENAI_API_KEY }}"
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        OPENAI_API_KEY: ${{ inputs.OPENAI_API_KEY }}
    - name: Configure git for autocoder-bot
      run: |
        git config user.name "autocoder-bot"
        git config user.email "actions@github.com"
      shell: bash
    - name: Create Pull Request with generated files
      uses: peter-evans/create-pull-request@v7
      with:
        branch: autocoder-branch-${{ inputs.ISSUE_NUMBER }}
        base: main
        commit-message: "Autocoder bot: Generated files for issue #${{ inputs.ISSUE_NUMBER }}"
        title: "Autocoder bot: PR for issue #${{ inputs.ISSUE_NUMBER }}"
        body: "This pull request contains files generated by autocoder bot for issue #${{ inputs.ISSUE_NUMBER }}."
        labels: autocoder-bot
        author: "autocoder-bot <actions@github.com>"
        committer: "autocoder-bot <actions@github.com>"
