name: AutoCoder
description: |
  A reusable composite GitHub Action that automates issue-driven code generation
  using OpenAI ChatGPT API and creates pull requests with the generated code.
author: Your Name <your.email@example.com>
inputs:
  GITHUB_TOKEN:
    description: 'Personal access token (PAT) for GitHub API authentication'
    required: true
  REPOSITORY:
    description: 'Repository where the action runs (e.g. owner/repo)'
    required: true
  ISSUE_NUMBER:
    description: 'The issue number that triggered the action'
    required: true
  OPENAI_API_KEY:
    description: 'API key for OpenAI usage to generate code'
    required: true
  SCRIPT_PATH:
    description: 'Path to the script that interacts with ChatGPT and generates code'
    required: true
    default: 'scripts/script.sh'
  LABEL:
    description: 'Label that triggers the autocoder bot action'
    required: false
    default: 'autocoder-bot'

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Make script executable
      run: chmod +x ${{ inputs.SCRIPT_PATH }}

    - name: Run Autocoder Script
      env:
        GITHUBTOKEN: ${{ inputs.GITHUB_TOKEN }}
        REPOSITORY: ${{ inputs.REPOSITORY }}
        ISSUENUMBER: ${{ inputs.ISSUE_NUMBER }}
        OPENAIAPIKEY: ${{ inputs.OPENAI_API_KEY }}
      run: ${{ inputs.SCRIPT_PATH }} "$GITHUBTOKEN" "$REPOSITORY" "$ISSUENUMBER" "$OPENAIAPIKEY"

    - name: Configure git for autocoder-bot
      run: |
        git config user.name "autocoder-bot"
        git config user.email "actions@github.com"

    - name: Create Pull Request with generated files
      uses: peter-evans/create-pull-request@v7
      with:
        branch: autocoder-branch-${{ inputs.ISSUE_NUMBER }}
        base: main
        commit-message: "Autocoder bot: Generated files for issue #${{ inputs.ISSUE_NUMBER }}"
        title: "Autocoder bot: PR for issue #${{ inputs.ISSUE_NUMBER }}"
        body: "This pull request contains files generated by autocoder bot for issue #${{ inputs.ISSUE_NUMBER }}."
        labels: ${{ inputs.LABEL }}
        author: "autocoder-bot <actions@github.com>"
        committer: "autocoder-bot <actions@github.com>"
