name: 'AutoCoder'
description: 'This action automates generating code from GitHub issues using OpenAI ChatGPT and creating PRs'
author: 'Your Name or Organization'
inputs:
  GITHUB_TOKEN:
    description: 'Personal access token (PAT) used for GitHub API authentication. This token is required to create pull requests and handle other repository interactions.'
    required: true
  REPOSITORY:
    description: 'The repository where the action will be executed.'
    required: true
  ISSUE_NUMBER:
    description: 'The number of the issue that triggered the action.'
    required: true
  OPENAI_API_KEY:
    description: 'API key for OpenAI, enabling interactions with the ChatGPT service to generate code based on issue descriptions.'
    required: true
  SCRIPT_PATH:
    description: 'The path to the script that interacts with ChatGPT and generates code.'
    required: true
  LABEL:
    description: 'Label that triggers the action.'
    required: true
    default: 'autocoder-bot'
outputs:
  pull_request_url:
    description: 'URL of the auto-created pull request containing generated code for review.'
runs:
  using: 'composite'
  steps:
    - name: Greet Users
      run: echo "Hello, welcome to AutoCoder! Let's generate some code."
      shell: bash
    - name: Make script executable
      run: chmod +x ${{ inputs.SCRIPT_PATH }}
      shell: bash
    - name: Generate Code from Issue
      run: |
        ${{ inputs.SCRIPT_PATH }} "${{ inputs.GITHUB_TOKEN }}" "${{ inputs.REPOSITORY }}" "${{ inputs.ISSUE_NUMBER }}" "${{ inputs.OPENAI_API_KEY }}"
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        OPENAI_API_KEY: ${{ inputs.OPENAI_API_KEY }}
    - name: Create Pull Request
      run: |
        # Script or commands to create pull request here
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
